// Code generated by protoc-gen-go.
// source: contract.proto
// DO NOT EDIT!

/*
Package contract is a generated protocol buffer package.

It is generated from these files:
	contract.proto

It has these top-level messages:
	Task
	Response
	Error
	UploadCsvData
	GetTasks
*/
package contract

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Task struct {
	Task             *string `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
	Priority         *string `protobuf:"bytes,2,opt,name=priority" json:"priority,omitempty"`
	TaskId           *int32  `protobuf:"varint,3,opt,name=taskId" json:"taskId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Task) GetTask() string {
	if m != nil && m.Task != nil {
		return *m.Task
	}
	return ""
}

func (m *Task) GetPriority() string {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return ""
}

func (m *Task) GetTaskId() int32 {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return 0
}

type Response struct {
	Data             []byte `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Err              *Error `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type Error struct {
	Status           *int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Description      *string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Error) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type UploadCsvData struct {
	CsvData          *string `protobuf:"bytes,1,opt,name=csvData" json:"csvData,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UploadCsvData) Reset()                    { *m = UploadCsvData{} }
func (m *UploadCsvData) String() string            { return proto.CompactTextString(m) }
func (*UploadCsvData) ProtoMessage()               {}
func (*UploadCsvData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UploadCsvData) GetCsvData() string {
	if m != nil && m.CsvData != nil {
		return *m.CsvData
	}
	return ""
}

type GetTasks struct {
	Bytedata         []byte `protobuf:"bytes,1,opt,name=bytedata" json:"bytedata,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetTasks) Reset()                    { *m = GetTasks{} }
func (m *GetTasks) String() string            { return proto.CompactTextString(m) }
func (*GetTasks) ProtoMessage()               {}
func (*GetTasks) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetTasks) GetBytedata() []byte {
	if m != nil {
		return m.Bytedata
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "contract.task")
	proto.RegisterType((*Response)(nil), "contract.response")
	proto.RegisterType((*Error)(nil), "contract.error")
	proto.RegisterType((*UploadCsvData)(nil), "contract.uploadCsvData")
	proto.RegisterType((*GetTasks)(nil), "contract.getTasks")
}

var fileDescriptor0 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0x8e, 0xbf, 0x4e, 0xc4, 0x30,
	0x0c, 0xc6, 0x75, 0x1c, 0x85, 0xe0, 0x3b, 0xae, 0x28, 0x2c, 0x1d, 0x3a, 0x54, 0x99, 0x18, 0x50,
	0x07, 0x06, 0x5e, 0x00, 0x16, 0x76, 0x5e, 0x20, 0x24, 0x11, 0x8a, 0x40, 0x75, 0x64, 0xbb, 0x48,
	0x7d, 0x7b, 0xf2, 0x47, 0x70, 0x53, 0xec, 0x2f, 0xfa, 0xf9, 0xfb, 0xc1, 0xc9, 0xe1, 0x22, 0x64,
	0x9d, 0xcc, 0x89, 0x50, 0x50, 0xab, 0xbf, 0xdd, 0x3c, 0xc3, 0xa5, 0x58, 0xfe, 0xd2, 0xc7, 0xf6,
	0x0e, 0xbb, 0x69, 0xf7, 0x70, 0xa3, 0xef, 0x40, 0x25, 0x8a, 0x48, 0x51, 0xb6, 0xe1, 0xa2, 0x26,
	0x27, 0xb8, 0x2a, 0xff, 0x6f, 0x7e, 0xd8, 0xe7, 0xbd, 0xcb, 0x9c, 0xa2, 0xc0, 0x09, 0x17, 0x0e,
	0x85, 0xf5, 0x56, 0x6c, 0x65, 0x8f, 0x7a, 0x84, 0x7d, 0x20, 0xaa, 0xd8, 0xe1, 0xa9, 0x9f, 0xff,
	0x9b, 0x73, 0x88, 0x64, 0x1e, 0xa1, 0xab, 0x43, 0x39, 0xc8, 0x62, 0x65, 0xe5, 0x8a, 0x75, 0xfa,
	0x1e, 0x0e, 0x3e, 0xb0, 0xa3, 0x98, 0x24, 0xe2, 0xd2, 0x5a, 0xcd, 0x04, 0xb7, 0x6b, 0xfa, 0x46,
	0xeb, 0x5f, 0xf8, 0xe7, 0x35, 0x57, 0xe8, 0x1e, 0xae, 0x5d, 0x1b, 0x9b, 0xa9, 0x19, 0x41, 0x7d,
	0x06, 0x79, 0xcf, 0x6a, 0x5c, 0xac, 0x3f, 0x36, 0x09, 0x67, 0x97, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x98, 0xcd, 0x0e, 0x7b, 0xf8, 0x00, 0x00, 0x00,
}
