// Code generated by protoc-gen-go.
// source: contract.proto
// DO NOT EDIT!

/*
Package contract is a generated protocol buffer package.

It is generated from these files:
	contract.proto

It has these top-level messages:
	Task
	Response
	Error
	Upload
*/
package contract

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Task struct {
	Task             *string `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
	Priority         *string `protobuf:"bytes,2,opt,name=priority" json:"priority,omitempty"`
	TaskId           *int32  `protobuf:"varint,3,opt,name=taskId" json:"taskId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Task) GetTask() string {
	if m != nil && m.Task != nil {
		return *m.Task
	}
	return ""
}

func (m *Task) GetPriority() string {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return ""
}

func (m *Task) GetTaskId() int32 {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return 0
}

type Response struct {
	Data             []byte `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Err              *Error `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type Error struct {
	Status           *int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Description      *string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Error) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type Upload struct {
	Data             []byte `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Upload) Reset()                    { *m = Upload{} }
func (m *Upload) String() string            { return proto.CompactTextString(m) }
func (*Upload) ProtoMessage()               {}
func (*Upload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Upload) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "contract.task")
	proto.RegisterType((*Response)(nil), "contract.response")
	proto.RegisterType((*Error)(nil), "contract.error")
	proto.RegisterType((*Upload)(nil), "contract.upload")
}

var fileDescriptor0 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x8d, 0x31, 0xcb, 0xc2, 0x40,
	0x0c, 0x86, 0xe9, 0xd7, 0xaf, 0xa5, 0xa6, 0xa5, 0xca, 0x09, 0xd2, 0xc1, 0x41, 0x3a, 0x39, 0x48,
	0x07, 0x07, 0xff, 0x83, 0x3f, 0x23, 0xf4, 0x6e, 0x38, 0x94, 0xe6, 0x48, 0xd2, 0xc1, 0x7f, 0x6f,
	0xef, 0x8a, 0x82, 0x53, 0xf2, 0xbe, 0xe1, 0xc9, 0x03, 0xed, 0x48, 0x93, 0x32, 0x8e, 0x3a, 0x04,
	0x26, 0x25, 0x53, 0x7d, 0x72, 0x7f, 0x83, 0x7f, 0x45, 0x79, 0x98, 0x66, 0x9d, 0x5d, 0x76, 0xca,
	0xce, 0x1b, 0xb3, 0x83, 0x2a, 0xb0, 0x27, 0xf6, 0xfa, 0xea, 0xfe, 0x52, 0xd3, 0x42, 0x19, 0xef,
	0x77, 0xdb, 0xe5, 0x4b, 0x2e, 0x16, 0xae, 0x62, 0x27, 0x81, 0x26, 0x71, 0x91, 0xb5, 0xa8, 0x98,
	0xd8, 0xc6, 0x1c, 0x21, 0x77, 0xcc, 0x09, 0xab, 0xaf, 0xdb, 0xe1, 0x6b, 0x5e, 0x4a, 0xe2, 0xfe,
	0x02, 0x45, 0x5a, 0xe2, 0x43, 0x51, 0xd4, 0x59, 0x12, 0x56, 0x98, 0x3d, 0xd4, 0xd6, 0xc9, 0xc8,
	0x3e, 0xa8, 0xa7, 0x69, 0xb5, 0xf6, 0x07, 0x28, 0xe7, 0xf0, 0x24, 0xb4, 0xbf, 0x8e, 0x77, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xbe, 0xa7, 0xd4, 0x07, 0xd0, 0x00, 0x00, 0x00,
}
